@startuml
class Ship {
    id:Int
    health:Health
    forwardSpeed:VectorialSpeed
    rotationalSpeed:RotationalSpeed
    shape:Shape
    weapon:Weapon
}

class Asteroid {
    id:Int
    health:Health
    forwardSpeed:VectorialSpeed
    rotationalSpeed:RotationalSpeed
    shape:Shape
}

@enduml
