@startuml
class Ship {
    id:Int
    health:Health
    speed:Speed
    shape:Shape
    weapon:Weapon
}

class Asteroid {
    id:Int
    health:Health
    speed:Speed
    shape:Shape
}

class Shot {
    id:Int
    health:Health
    speed:Speed
    shape:Shape
}

class speed {
    forwardSpeed:VectorialSpeed
    rotationalSpeed:RotationalSpeed
}
@enduml
