@startuml
class Ship {
    id:Int
    weapon:Weapon
}

class Asteroid {
    id:Int
}

class Shot {
    id:Int
}

class GameComponent {
    health:Health
    speed:Speed
    shape:Shape
}

class Speed {
    forwardSpeed:VectorialSpeed
    rotationalSpeed:RotationalSpeed
}
@enduml
